# Generated by Django 6.0 on 2025-12-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='curren_streak',
            new_name='current_streak',
        ),
    ]
