# Generated by Django 6.0 on 2025-12-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_rename_curren_streak_userprofile_current_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='male_1', max_length=100),
        ),
    ]
