# Generated by Django 6.0 on 2025-12-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='male_1.png', max_length=100),
        ),
    ]
